version: 0.1

roles:

  viewer:
    name: Viewer
    materials_read: Yes
    materials_create_new: No
    materials_edit_own: No
    materials_edit_all: No
    materials_delete: No
    evaluations_read: Yes
    evaluations_create_new: No
    evaluations_edit_own: No
    evaluations_edit_all: No
    evaluations_delete: No

  evaluator:
    name: Evaluator
    materials_read: Yes
    materials_create_new: No
    materials_edit_own: No
    materials_edit_all: No
    materials_delete: No
    evaluations_read: Yes
    evaluations_create_new: Yes
    evaluations_edit_own: Yes
    evaluations_edit_all: No
    evaluations_delete: No

  modeler:
    name: Modeler
    materials_read: Yes
    materials_create_new: Yes
    materials_edit_own: Yes
    materials_edit_all: No
    materials_delete: No
    evaluations_read: Yes
    evaluations_create_new: No
    evaluations_edit_own: No
    evaluations_edit_all: No
    evaluations_delete: No

  admin:
    name: Admin
    materials_read: Yes
    materials_create_new: Yes
    materials_edit_own: Yes
    materials_edit_all: Yes
    materials_delete: Yes
    evaluations_read: Yes
    evaluations_create_new: Yes
    evaluations_edit_own: Yes
    evaluations_edit_all: Yes
    evaluations_delete: Yes

tables:

  users:
    user_id:
      name: User ID
      description: User ID (a unique ID or the email).
      type: text
      constraint: PRIMARY KEY
    user_name:
      name: User Name
      description: The user's full name.
      type: text
      constraint: NOT NULL
    user_email:
      name: User Email
      description: The user's email address.
      type: text
      constraint: UNIQUE NOT NULL
    user_affiliation:
      name: User Affiliation
      description: The user's primary affiliation, e.g. ECCC, BAM, etc.
      type: text
      constraint: NOT NULL
    user_roles:
      name: User Role
      description: A comma separated list of user roles, e.g. `modeler,evaluator`. The default role is `viewer` and is assumed even if not mentioned explicitly (value is null).
      type: text
      constraint:

  species:
    species_id:
      name: Species ID
      description: Lower case 4-letter code, e.g. `oven` for Ovenbird.
      type: text
      constraint: PRIMARY KEY
    scientific_name:
      name: Scientific Name
      description: Scientific name.
      type: text
      constraint: UNIQUE NOT NULL
    english_name:
      name: English Name
      description: Common name in English.
      type: text
      constraint: UNIQUE NOT NULL
    french_name:
      name: French Name
      description: Common name in French (use UTF-8 encoding).
      type: text
      constraint: UNIQUE NOT NULL

  models:
    model_id:
      name: Model ID
      description: Model ID, lower case, alphanumeric, `.` and `_` allowed.
      type: text
      constraint: PRIMARY KEY
    model_name:
      name: Model Name
      description: A human readable version of `model_id` displayed in the app.
      type: text
      constraint: UNIQUE NOT NULL
    model_description:
      name: Model Description
      description: A human readable version of `model_id` displayed in the app.
      type: text
      constraint: UNIQUE NOT NULL
    model_metadata:
      name: Model Metadata
      description: A file path or URL pointing used to find the ODMAP metadata for the model.
      type: text
      constraint: UNIQUE NOT NULL

  components:
    component_id:
      name: Component ID
      description: Component ID, lower case with `_`, also used in Shiny module names.
      type: text
      constraint: PRIMARY KEY
    component_description:
      name: Component Description
      description: Component description.
      type: text
      constraint: NOT NULL
    component_mandatory:
      name: Mandatory
      description: Is the component mandatory (value is `TRUE`).
      type: boolean
      constraint: NOT NULL

  materials:
    material_id:
      name: Material ID
      description: ID for joining feedback to materials (in the form of `<species_id>_<model_id>_<component_id>`).
      type: text
      constraint: PRIMARY KEY
    model_id:
      name: Model ID
      description: Model ID (foreign key).
      type: text
      constraint: REFERENCES models
    species_id:
      name: Species ID
      description: Species ID (foreign key).
      type: text
      constraint: REFERENCES species
    component_id:
      name: Component ID
      description: Component ID (foreign key).
      type: text
      constraint: REFERENCES components
    material_create_user:
      name: Create User
      description: User who uploaded the model material (foreign key).
      type: text
      constraint: REFERENCES user (user_id)
    material_create_time:
      name: Create Time
      description: Time of initial upload.
      type: timestamp
      constraint: NOT NULL
    material_modify_user:
      name: Modify User
      description: User who modified the model material (foreign key).
      type: text
      constraint: REFERENCES user (user_id)
    material_modify_time:
      name: Modify Time
      description: Time of last modification.
      type: timestamp
      constraint: NOT NULL

  evaluations:
    material_id:
      name: Material ID
      description: Material ID.
      type: text
      constraint: REFERENCES materials
    evaluation_create_user:
      name: Create User
      description: Time of initial evaluation (foreign key).
      type: text
      constraint: REFERENCES user (user_id)
    evaluation_create_time:
      name: Create Time
      description: Time of initial upload.
      type: timestamp
      constraint: NOT NULL
    evaluation_modify_user:
      name: Modify User
      description: User who last modified (foreign key).
      type: text
      constraint: REFERENCES user (user_id)
    evaluation_modify_time:
      name: Modify Time
      description: Time of last modification.
      type: timestamp
      constraint: NOT NULL
    evaluation_body:
      name: Evaluation
      description: JSON blob with the evaluation according to component display rules reflecting last modification.
      type: json
      constraint: NOT NULL
    comment_create_user:
      name: Create User
      description: Time of initial evaluation (foreign key).
      type: text
      constraint: REFERENCES user (user_id)
    comment_create_time:
      name: Create Time
      description: Time of initial upload.
      type: timestamp
      constraint: NOT NULL
    comment_modify_user:
      name: Modify User
      description: User who last modified (foreign key).
      type: text
      constraint: REFERENCES user (user_id)
    comment_modify_time:
      name: Modify Time
      description: Time of last modification.
      type: timestamp
      constraint: NOT NULL
    comment_body:
      name: Comment
      description: JSON blob with the comment on an evaluation according to component display rules reflecting last modification.
      type: json
      constraint: NOT NULL

components:

  observations:
    description: Detections or counts by location and timestamp for a single or multiple species.
    mandatory: Yes
    upload:
      type: table
      input:
        description: >
          Observations are organized as survey events as rows (unique combinations
          of location [longitude/latitude] and date/time). The table has the
          following mandatory fields: latitude, longitude, time, and method.
          Latitude and longitude are coordinates as decimal degrees (EPSG:4326).
          Time is in a format coercible to POSIX time, e.g. 2019-06-01 7:21:00 AM.
          Method is a string denoting the survey method. Other columns holding
          the observations should be named using Species IDs, i.e. 4-letter codes
          (e.g. OVEN, TEWA, etc.) consistent with the species list being used.
          The cell values in the species columns should be non-negative integers
          (i.e. 0, 1, 2, ... or 0/1) indicating the detections (>0) and 
          non-detections of the species during the survey events.
          The single-species and multi-species data format are identical except
          for the number of species whose data is in the table.
          The table can be in csv (make sure that time is formatted properly),
          rds and parquet (these latter formats should have time as POSIX).
        file_ext: [csv, rds, parquet]
        columns: [latitude:double, longitude:double, time:timestamp, method:text]
      output:
        description: >
          The output is a spatial point data frame with columns:
          time, method, and status (coordinates are part of the geometry column).
        columns: [time:timestamp, method:text, status:integer]
        path: "materials/{model_id}/{species_id}/observations.gpkg"
    display:
      type: map
      title: Observations
      description: >
        Display non-detections (status == 0) detections (status > 0) in
        different colors. Show detections by default (green), allow an option to turn
        on non-detections (grey). Use circle markers in Leaflet.
        We can use unique(method) and year of survey as dropdown filters.
        Method, time, status should be part of popup message on click.
      placement: "page.tab.section" # TBD
    evaluation:
    reporting:

  model_metadata:
    description: ODMAP protocol metadata.
    mandatory: Yes
    upload:
      type: table
      input:
        description: TBD once we integrate ODMAP into the UI.
        file_ext: [csv, rds, parquet]
        columns: []
      output:
        description: TBD once we integrate ODMAP into the UI.
        columns: []
        path: "materials/{model_id}/model_metadata.parquet"
    display:
      type: table
      title: Model Metadata
      description: TBD once we integrate ODMAP into the UI.
      placement: "page.tab.section" # TBD
    evaluation:
    reporting:

  predictor_metadata:
    description: Predictor metadata.
    mandatory: Yes
    upload:
      type: table
      input:
        description: >
          The file should contain the recommended columns but is not
          strictly enforced. The table should give information about the
          predictors (one predictor per row). The file can be csv, rds, or parquet.
          The predictor column should list the short names of the predictors
          that match the band names in the predictor raster.
        file_ext: [csv, rds, parquet]
        columns: [predictor, definition, predictor_class, resolution, source, provider, citation, covariate_extraction, prediction_resolution, years, temporal_matching]
      output:
        description: A file is written with the listed columns.
        columns: [predictor, definition, predictor_class, resolution, source, provider, citation, covariate_extraction, prediction_resolution, years, temporal_matching]
        path: "materials/{model_id}/predictor_metadata.parquet"
    display:
      type: table
      title: Predictor Metadata
      description: >
        The table is displayed as a reactable table.
      placement: "page.tab.section" # TBD
    evaluation:
    reporting:

  predictor_raster:
    description: Predictor raster, a multi-band TIF with spatial predictors as bands.
    mandatory: Yes
    upload:
      type: raster
      input:
        description: >
          A spatial raster file in tif format where bands are different spatial
          predictors. Names of the layers should match the predictor column in 
          the predictor metadata.
        file_ext: [tif]
        columns: []
      output:
        description: >
          The tif file is saved as is.
        path: "materials/{model_id}/predictor_raster.tif"
    display:
      type: map
      title: Predictor Raster
      description: >
        A raster map in Leaflet, bands are added as layers and can be selected
        from the layers icon of the map.
      placement: "page.tab.section" # TBD
    evaluation:
    reporting:

  spatial_prediction:
    description: Expected value as band 1, variation as band 2.
    mandatory: Yes
    upload:
      type: raster
      input:
        description: >
          A spatial raster in tif format. The 1st band is interpreted as
          the distribution layer (abundance, occurrence probability, density)
          with non-negative real values.
          The second layer, if present, is interpreted as a layer with
          uncertainty (non-negative values, SE, CoV, CI or PI width, etc.).
        file_ext: [tif]
        columns: []
      output:
        description: >
          The file is saved as is. The metadata will be used to
          label the map appropriately (what the units are etc.).
        path: "materials/{model_id}/{species_id}/spatial_prediction.tif"
    display:
      type: map
      title: Spatial Prediction
      description: >
        A raster map in Leaflet, with 2 bands: one for "abundance" one for
        "uncertainty".
      placement: "page.tab.section" # TBD
    evaluation:
    reporting:

  model_summary:
    description: Model summary including variable importance metrics or coefficients for predictor variables.
    mandatory: Yes
    upload:
      type: table
      input:
        description: >
          A table summarizing the models, usually predictors as rows
          (listed in the column called predictor). The multi-species
          version lists Species IDs in the column species_id.
          The predictors should match names in the predictor metadata.
          Other columns can be named freely, e.g. var_importance, coefficient,
          StdError etc.
        file_ext: [csv, rds, parquet]
        columns: [species_id, predictor]
      output:
        description: >
          The input file is filtered for individual species and saved.
        path: "materials/{model_id}/{species_id}/model_summary.parquet"
    display:
      type: table
      title: Model Summary
      description: >
        The table is displayed as a reactable table.
      placement: "page.tab.section" # TBD
    evaluation:
    reporting:

  model_fit:
    description: Model fit statistics.
    mandatory: Yes
    upload:
      type: table
      input:
        description: >
          A table summarizing the model fit, statistics as rows
          (listed in the column called statistic). The multi-species
          version lists Species IDs in the column species_id.
          The value of the fit statistic is in the column called value.
          Fit metrics are also listed in the project metadata.
        file_ext: [csv, rds, parquet]
        columns: [species_id, statistic, value]
      output:
        description: >
          The input file is filtered for individual species and saved.
        path: "materials/{model_id}/{species_id}/model_fit.parquet"
    display:
      type: table
      title: Model Fit
      description: >
        The table is displayed as a reactable table.
      placement: "page.tab.section" # TBD
    evaluation:
    reporting:
