---
output:
  md_document:
    variant: gfm
---

# SDM Model Evaluation Tool User Guide for Synthesis

> How to synthesize evaluations

## Installation

Install the following R packages:

- rmarkdown
- sf
- terra
- sdmEvalToolCore
- sdmEvalToolUI

## Finding material/deployment related files

The files are organized according to the [SDM Tool Specifications](../spec/)

## Working with the database

Connect to the database:
```r
con <- db_connect()
```

Read the deployments table and filter to a select `deployment_id`:
```r
t_dp <- db_read_table(con, "deployments") |>
    dplyr::filter(deployment_id == .env$deployment_id)
```

Read the models table and filter to a select `model_id`:
```r
t_mo <- db_read_table(con, "models") |>
    dplyr::filter(model_id == .env$model_id)
```

Read the species table and filter to a select `species_id`:
```r
t_sp <- db_read_table(con, "species") |>
    dplyr::filter(species_id == .env$species_id)
```

Read the user information for a deployment:
```r
t_u <- db_read_user_info(con, user_id = user_id, deployment_id = deployment_id)
```

Read evaluations for a user and deployment:
```r
d <- db_read_evaluations(
    con,
    deployment_id = deployment_id,
    user_id = user_id
)
```

A nicely formatted version of the evaluations:
```r
q <- prep_evaluations(user_id = user_id)
e <- prep_evaluations(user_id = user_id) |>
    tidyr::unnest("answers")
```

Disconnect from the database:
```r
db_disconnect(con)
```

## Single evaluations

See the [parametrized Rmd template](../working/report-single-evaluation.Rmd).

The template takes the following parameters:

- `user_id`: user ID for the single evaluation
- `model_id`: model ID
- `species_id`: species ID
- `deployment_id`: deployment ID
- `base_path`: base path relative to the Rmd file

You can provide these when rendering the file:

```r
rmarkdown::render(
    input = "working/report-single-evaluation.Rmd", 
    params = list(
    user_id = "testuser",
    model_id = "bam_v5_can71",
    species_id = "BBWA",
    deployment_id = "deployment1",
    base_path = "../misc/test"
))
```

Follow along the Rmd file to see how to display various types of model
materials and the corresponding evaluations.

The following function implements the identification of questions and answers,
recognizing the type of questions (spatial or non-spatial):

```r
prep_evaluations_further <- function(x, subunit = NULL) {
    if (nrow(x) != 1L) {
        stop("x must have")
    }
    i <- 1L
    v <- x$response[i][[1]]
    if (length(v) == 1L) {
        m <- NULL
    } else {
        if (nrow(v) == 1L) {
            m <- NULL
        } else {
            if (is.null(subunit)) {
                stop("Spatial evaluations require subunit to be provided.")
            }
            m <- subunit
            m$values <- NA_character_
            for (j in nrow(v):1) {
                m$values[m$subunit_id %in% v$subunits[j][[1L]]] <- v$values[j]
            }
        }
    }
    list(question = x$label[i], response = v, map = m)
}
```

The function returns a list with the question, response, and the map
when the evaluation is spatial.

Here is the structure for a non-spatial question:

```R
# List of 3
#  $ question: chr "How concerned are you about the distribution of counts?"
#  $ response:'data.frame':       1 obs. of  2 variables:
#   ..$ values  : logi NA
#   ..$ subunits: chr "Not at all"
#  $ map     : NULL
```

Here is the structure for a spatial question:

```R
# List of 3
#  $ question: chr "Are there areas where this species is not sufficiently 
#                   sampled? Identify areas that are not sufficiently sampled."
#  $ response:'data.frame':       4 obs. of  2 variables:
#   ..$ values  : chr [1:4] "Very undersampled" "Moderately undersampled" 
#                           "Accurate" "Unknown"
#   ..$ subunits:List of 4
#   .. ..$ : Named list()
#   .. ..$ : Named list()
#   .. ..$ : chr [1:3] "91" "92" "130"
#   .. ..$ : Named list()
#  $ map     : sf [272 × 4] (S3: sf/tbl_df/tbl/data.frame)
#   ..$ subunit_id: chr [1:272] "9" "10" "11" "12" ...
#   ..$ geom      :sfc_POLYGON of length 272; first list element: List of 1
#   .. ..$ : num [1:5, 1:2] -86.7 -85.6 -85.6 -86.7 -86.7 ...
#   .. ..- attr(*, "class")= chr [1:3] "XY" "POLYGON" "sfg"
#   ..$ id        : chr [1:272] "9" "10" "11" "12" ...
#   ..$ values    : chr [1:272] NA NA NA NA ...
#   ..- attr(*, "sf_column")= chr "geom"
#   ..- attr(*, "agr")= Factor w/ 3 levels "constant","aggregate",..: NA NA NA
#   .. ..- attr(*, "names")= chr [1:3] "subunit_id" "id" "values"
```

The Rmd file also shows how to calculate the minutes it takes for the evaluation to
be completed based on the saved timestamps:

```R
Tmin <- min(d$evaluation_create_time)
Tmax <- max(d$evaluation_modify_time, na.rm = TRUE)
Tdiff <- difftime(Tmax, Tmin, units = "mins")
```

## Multiple evaluations

Use the logic from the `prep_evaluations_further()` function above
to parse evaluations from multiple users. Ordinal responses can be tallied,
spatial responses can also be processed to find the frequency distribution
of the values for each polygon.

Note that the order of evaluations for different users cannot be expected
to be identical, because the ordering of the database table depends on
the timestamps of the responses. Some responses could be missing
(unsaved or abandoned before finishing).

Note also that the summary feedback might have to taken into consideration
for other responses. This is the spatial response that delineates the
user's "comfort zone" regarding the species.
